/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: a.i

package phpor

/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


extern void _wrap_Swig_free_phpor_efd8b398f84f2714(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_phpor_efd8b398f84f2714(swig_intgo arg1);
extern swig_intgo _wrap_say_phpor_efd8b398f84f2714(uintptr_t arg1);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_phpor_efd8b398f84f2714(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_phpor_efd8b398f84f2714(C.swig_intgo(_swig_i_0)))
	return swig_r
}

func Say(arg1 String) (_swig_ret int) {
	var swig_r int
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (int)(C._wrap_say_phpor_efd8b398f84f2714(C.uintptr_t(_swig_i_0)))
	return swig_r
}


type SwigcptrString uintptr
type String interface {
	Swigcptr() uintptr;
}
func (p SwigcptrString) Swigcptr() uintptr {
	return uintptr(p)
}

