/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: caid.i

package caid

//#cgo linux LDFLAGS: -L${SRCDIR} -lcaid
//#cgo darwin LDFLAGS: -L${SRCDIR} -lcaid_darwin
/*
#define intgo swig_intgo
typedef void *swig_voidp;

#include <stdint.h>


typedef long long intgo;
typedef unsigned long long uintgo;



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;


typedef long long swig_type_1;
typedef long long swig_type_2;
typedef long long swig_type_3;
typedef long long swig_type_4;
typedef _gostring_ swig_type_5;
typedef _gostring_ swig_type_6;
typedef _gostring_ swig_type_7;
typedef _gostring_ swig_type_8;
typedef _gostring_ swig_type_9;
typedef _gostring_ swig_type_10;
typedef _gostring_ swig_type_11;
typedef _gostring_ swig_type_12;
typedef _gostring_ swig_type_13;
typedef _gostring_ swig_type_14;
typedef _gostring_ swig_type_15;
typedef _gostring_ swig_type_16;
typedef _gostring_ swig_type_17;
typedef _gostring_ swig_type_18;
typedef _gostring_ swig_type_19;
typedef _gostring_ swig_type_20;
typedef _gostring_ swig_type_21;
typedef _gostring_ swig_type_22;
typedef _gostring_ swig_type_23;
typedef _gostring_ swig_type_24;
typedef _gostring_ swig_type_25;
typedef _gostring_ swig_type_26;
typedef _gostring_ swig_type_27;
typedef _gostring_ swig_type_28;
typedef _gostring_ swig_type_29;
typedef _gostring_ swig_type_30;
typedef _gostring_ swig_type_31;
typedef _gostring_ swig_type_32;
typedef _gostring_ swig_type_33;
typedef _gostring_ swig_type_34;
extern void _wrap_Swig_free_caid_daffae03a615fb3a(uintptr_t arg1);
extern uintptr_t _wrap_Swig_malloc_caid_daffae03a615fb3a(swig_intgo arg1);
extern uintptr_t _wrap_new_CaidVector__SWIG_0_caid_daffae03a615fb3a(void);
extern uintptr_t _wrap_new_CaidVector__SWIG_1_caid_daffae03a615fb3a(swig_type_1 arg1);
extern uintptr_t _wrap_new_CaidVector__SWIG_2_caid_daffae03a615fb3a(uintptr_t arg1);
extern swig_type_2 _wrap_CaidVector_size_caid_daffae03a615fb3a(uintptr_t arg1);
extern swig_type_3 _wrap_CaidVector_capacity_caid_daffae03a615fb3a(uintptr_t arg1);
extern void _wrap_CaidVector_reserve_caid_daffae03a615fb3a(uintptr_t arg1, swig_type_4 arg2);
extern _Bool _wrap_CaidVector_isEmpty_caid_daffae03a615fb3a(uintptr_t arg1);
extern void _wrap_CaidVector_clear_caid_daffae03a615fb3a(uintptr_t arg1);
extern void _wrap_CaidVector_add_caid_daffae03a615fb3a(uintptr_t arg1, uintptr_t arg2);
extern uintptr_t _wrap_CaidVector_get_caid_daffae03a615fb3a(uintptr_t arg1, swig_intgo arg2);
extern void _wrap_CaidVector_set_caid_daffae03a615fb3a(uintptr_t arg1, swig_intgo arg2, uintptr_t arg3);
extern void _wrap_delete_CaidVector_caid_daffae03a615fb3a(uintptr_t arg1);
extern uintptr_t _wrap_new_CaidMap__SWIG_0_caid_daffae03a615fb3a(void);
extern uintptr_t _wrap_new_CaidMap__SWIG_1_caid_daffae03a615fb3a(swig_type_5 arg1, swig_type_6 arg2);
extern uintptr_t _wrap_new_CaidMap__SWIG_2_caid_daffae03a615fb3a(uintptr_t arg1);
extern void _wrap_CaidMap_first_set_caid_daffae03a615fb3a(uintptr_t arg1, swig_type_7 arg2);
extern swig_type_8 _wrap_CaidMap_first_get_caid_daffae03a615fb3a(uintptr_t arg1);
extern void _wrap_CaidMap_second_set_caid_daffae03a615fb3a(uintptr_t arg1, swig_type_9 arg2);
extern swig_type_10 _wrap_CaidMap_second_get_caid_daffae03a615fb3a(uintptr_t arg1);
extern void _wrap_delete_CaidMap_caid_daffae03a615fb3a(uintptr_t arg1);
extern void _wrap_DeviceInfo_boot_time_in_sec_set_caid_daffae03a615fb3a(uintptr_t arg1, swig_type_11 arg2);
extern swig_type_12 _wrap_DeviceInfo_boot_time_in_sec_get_caid_daffae03a615fb3a(uintptr_t arg1);
extern void _wrap_DeviceInfo_country_code_set_caid_daffae03a615fb3a(uintptr_t arg1, swig_type_13 arg2);
extern swig_type_14 _wrap_DeviceInfo_country_code_get_caid_daffae03a615fb3a(uintptr_t arg1);
extern void _wrap_DeviceInfo_language_set_caid_daffae03a615fb3a(uintptr_t arg1, swig_type_15 arg2);
extern swig_type_16 _wrap_DeviceInfo_language_get_caid_daffae03a615fb3a(uintptr_t arg1);
extern void _wrap_DeviceInfo_device_name_set_caid_daffae03a615fb3a(uintptr_t arg1, swig_type_17 arg2);
extern swig_type_18 _wrap_DeviceInfo_device_name_get_caid_daffae03a615fb3a(uintptr_t arg1);
extern void _wrap_DeviceInfo_system_version_set_caid_daffae03a615fb3a(uintptr_t arg1, swig_type_19 arg2);
extern swig_type_20 _wrap_DeviceInfo_system_version_get_caid_daffae03a615fb3a(uintptr_t arg1);
extern void _wrap_DeviceInfo_machine_set_caid_daffae03a615fb3a(uintptr_t arg1, swig_type_21 arg2);
extern swig_type_22 _wrap_DeviceInfo_machine_get_caid_daffae03a615fb3a(uintptr_t arg1);
extern void _wrap_DeviceInfo_carrier_info_set_caid_daffae03a615fb3a(uintptr_t arg1, swig_type_23 arg2);
extern swig_type_24 _wrap_DeviceInfo_carrier_info_get_caid_daffae03a615fb3a(uintptr_t arg1);
extern void _wrap_DeviceInfo_memory_set_caid_daffae03a615fb3a(uintptr_t arg1, swig_type_25 arg2);
extern swig_type_26 _wrap_DeviceInfo_memory_get_caid_daffae03a615fb3a(uintptr_t arg1);
extern void _wrap_DeviceInfo_disk_set_caid_daffae03a615fb3a(uintptr_t arg1, swig_type_27 arg2);
extern swig_type_28 _wrap_DeviceInfo_disk_get_caid_daffae03a615fb3a(uintptr_t arg1);
extern void _wrap_DeviceInfo_sys_file_time_set_caid_daffae03a615fb3a(uintptr_t arg1, swig_type_29 arg2);
extern swig_type_30 _wrap_DeviceInfo_sys_file_time_get_caid_daffae03a615fb3a(uintptr_t arg1);
extern void _wrap_DeviceInfo_model_set_caid_daffae03a615fb3a(uintptr_t arg1, swig_type_31 arg2);
extern swig_type_32 _wrap_DeviceInfo_model_get_caid_daffae03a615fb3a(uintptr_t arg1);
extern void _wrap_DeviceInfo_time_zone_set_caid_daffae03a615fb3a(uintptr_t arg1, swig_type_33 arg2);
extern swig_type_34 _wrap_DeviceInfo_time_zone_get_caid_daffae03a615fb3a(uintptr_t arg1);
extern uintptr_t _wrap_new_DeviceInfo_caid_daffae03a615fb3a(void);
extern void _wrap_delete_DeviceInfo_caid_daffae03a615fb3a(uintptr_t arg1);
extern uintptr_t _wrap_GenerateCAID_caid_daffae03a615fb3a(uintptr_t arg1);
#undef intgo
*/
import "C"

import "unsafe"
import _ "runtime/cgo"
import "sync"


type _ unsafe.Pointer



var Swig_escape_always_false bool
var Swig_escape_val interface{}


type _swig_fnptr *byte
type _swig_memberptr *byte


type _ sync.Mutex


type swig_gostring struct { p uintptr; n int }
func swigCopyString(s string) string {
  p := *(*swig_gostring)(unsafe.Pointer(&s))
  r := string((*[0x7fffffff]byte)(unsafe.Pointer(p.p))[:p.n])
  Swig_free(p.p)
  return r
}

func Swig_free(arg1 uintptr) {
	_swig_i_0 := arg1
	C._wrap_Swig_free_caid_daffae03a615fb3a(C.uintptr_t(_swig_i_0))
}

func Swig_malloc(arg1 int) (_swig_ret uintptr) {
	var swig_r uintptr
	_swig_i_0 := arg1
	swig_r = (uintptr)(C._wrap_Swig_malloc_caid_daffae03a615fb3a(C.swig_intgo(_swig_i_0)))
	return swig_r
}

type SwigcptrCaidVector uintptr

func (p SwigcptrCaidVector) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrCaidVector) SwigIsCaidVector() {
}

func NewCaidVector__SWIG_0() (_swig_ret CaidVector) {
	var swig_r CaidVector
	swig_r = (CaidVector)(SwigcptrCaidVector(C._wrap_new_CaidVector__SWIG_0_caid_daffae03a615fb3a()))
	return swig_r
}

func NewCaidVector__SWIG_1(arg1 int64) (_swig_ret CaidVector) {
	var swig_r CaidVector
	_swig_i_0 := arg1
	swig_r = (CaidVector)(SwigcptrCaidVector(C._wrap_new_CaidVector__SWIG_1_caid_daffae03a615fb3a(C.swig_type_1(_swig_i_0))))
	return swig_r
}

func NewCaidVector__SWIG_2(arg1 CaidVector) (_swig_ret CaidVector) {
	var swig_r CaidVector
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (CaidVector)(SwigcptrCaidVector(C._wrap_new_CaidVector__SWIG_2_caid_daffae03a615fb3a(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func NewCaidVector(a ...interface{}) CaidVector {
	argc := len(a)
	if argc == 0 {
		return NewCaidVector__SWIG_0()
	}
	if argc == 1 {
		if _, ok := a[0].(int64); !ok {
			goto check_2
		}
		return NewCaidVector__SWIG_1(a[0].(int64))
	}
check_2:
	if argc == 1 {
		return NewCaidVector__SWIG_2(a[0].(CaidVector))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrCaidVector) Size() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_CaidVector_size_caid_daffae03a615fb3a(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrCaidVector) Capacity() (_swig_ret int64) {
	var swig_r int64
	_swig_i_0 := arg1
	swig_r = (int64)(C._wrap_CaidVector_capacity_caid_daffae03a615fb3a(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrCaidVector) Reserve(arg2 int64) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_CaidVector_reserve_caid_daffae03a615fb3a(C.uintptr_t(_swig_i_0), C.swig_type_4(_swig_i_1))
}

func (arg1 SwigcptrCaidVector) IsEmpty() (_swig_ret bool) {
	var swig_r bool
	_swig_i_0 := arg1
	swig_r = (bool)(C._wrap_CaidVector_isEmpty_caid_daffae03a615fb3a(C.uintptr_t(_swig_i_0)))
	return swig_r
}

func (arg1 SwigcptrCaidVector) Clear() {
	_swig_i_0 := arg1
	C._wrap_CaidVector_clear_caid_daffae03a615fb3a(C.uintptr_t(_swig_i_0))
}

func (arg1 SwigcptrCaidVector) Add(arg2 CaidMap) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2.Swigcptr()
	C._wrap_CaidVector_add_caid_daffae03a615fb3a(C.uintptr_t(_swig_i_0), C.uintptr_t(_swig_i_1))
}

func (arg1 SwigcptrCaidVector) Get(arg2 int) (_swig_ret CaidMap) {
	var swig_r CaidMap
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (CaidMap)(SwigcptrCaidMap(C._wrap_CaidVector_get_caid_daffae03a615fb3a(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1))))
	return swig_r
}

func (arg1 SwigcptrCaidVector) Set(arg2 int, arg3 CaidMap) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	_swig_i_2 := arg3.Swigcptr()
	C._wrap_CaidVector_set_caid_daffae03a615fb3a(C.uintptr_t(_swig_i_0), C.swig_intgo(_swig_i_1), C.uintptr_t(_swig_i_2))
}

func DeleteCaidVector(arg1 CaidVector) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_CaidVector_caid_daffae03a615fb3a(C.uintptr_t(_swig_i_0))
}

type CaidVector interface {
	Swigcptr() uintptr
	SwigIsCaidVector()
	Size() (_swig_ret int64)
	Capacity() (_swig_ret int64)
	Reserve(arg2 int64)
	IsEmpty() (_swig_ret bool)
	Clear()
	Add(arg2 CaidMap)
	Get(arg2 int) (_swig_ret CaidMap)
	Set(arg2 int, arg3 CaidMap)
}

type SwigcptrCaidMap uintptr

func (p SwigcptrCaidMap) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrCaidMap) SwigIsCaidMap() {
}

func NewCaidMap__SWIG_0() (_swig_ret CaidMap) {
	var swig_r CaidMap
	swig_r = (CaidMap)(SwigcptrCaidMap(C._wrap_new_CaidMap__SWIG_0_caid_daffae03a615fb3a()))
	return swig_r
}

func NewCaidMap__SWIG_1(arg1 string, arg2 string) (_swig_ret CaidMap) {
	var swig_r CaidMap
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	swig_r = (CaidMap)(SwigcptrCaidMap(C._wrap_new_CaidMap__SWIG_1_caid_daffae03a615fb3a(*(*C.swig_type_5)(unsafe.Pointer(&_swig_i_0)), *(*C.swig_type_6)(unsafe.Pointer(&_swig_i_1)))))
	if Swig_escape_always_false {
		Swig_escape_val = arg1
	}
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
	return swig_r
}

func NewCaidMap__SWIG_2(arg1 CaidMap) (_swig_ret CaidMap) {
	var swig_r CaidMap
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (CaidMap)(SwigcptrCaidMap(C._wrap_new_CaidMap__SWIG_2_caid_daffae03a615fb3a(C.uintptr_t(_swig_i_0))))
	return swig_r
}

func NewCaidMap(a ...interface{}) CaidMap {
	argc := len(a)
	if argc == 0 {
		return NewCaidMap__SWIG_0()
	}
	if argc == 1 {
		return NewCaidMap__SWIG_2(a[0].(CaidMap))
	}
	if argc == 2 {
		return NewCaidMap__SWIG_1(a[0].(string), a[1].(string))
	}
	panic("No match for overloaded function call")
}

func (arg1 SwigcptrCaidMap) SetFirst(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_CaidMap_first_set_caid_daffae03a615fb3a(C.uintptr_t(_swig_i_0), *(*C.swig_type_7)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrCaidMap) GetFirst() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_CaidMap_first_get_caid_daffae03a615fb3a(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrCaidMap) SetSecond(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_CaidMap_second_set_caid_daffae03a615fb3a(C.uintptr_t(_swig_i_0), *(*C.swig_type_9)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrCaidMap) GetSecond() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_CaidMap_second_get_caid_daffae03a615fb3a(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func DeleteCaidMap(arg1 CaidMap) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_CaidMap_caid_daffae03a615fb3a(C.uintptr_t(_swig_i_0))
}

type CaidMap interface {
	Swigcptr() uintptr
	SwigIsCaidMap()
	SetFirst(arg2 string)
	GetFirst() (_swig_ret string)
	SetSecond(arg2 string)
	GetSecond() (_swig_ret string)
}

type SwigcptrDeviceInfo uintptr

func (p SwigcptrDeviceInfo) Swigcptr() uintptr {
	return (uintptr)(p)
}

func (p SwigcptrDeviceInfo) SwigIsDeviceInfo() {
}

func (arg1 SwigcptrDeviceInfo) SetBoot_time_in_sec(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_DeviceInfo_boot_time_in_sec_set_caid_daffae03a615fb3a(C.uintptr_t(_swig_i_0), *(*C.swig_type_11)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrDeviceInfo) GetBoot_time_in_sec() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_DeviceInfo_boot_time_in_sec_get_caid_daffae03a615fb3a(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrDeviceInfo) SetCountry_code(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_DeviceInfo_country_code_set_caid_daffae03a615fb3a(C.uintptr_t(_swig_i_0), *(*C.swig_type_13)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrDeviceInfo) GetCountry_code() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_DeviceInfo_country_code_get_caid_daffae03a615fb3a(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrDeviceInfo) SetLanguage(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_DeviceInfo_language_set_caid_daffae03a615fb3a(C.uintptr_t(_swig_i_0), *(*C.swig_type_15)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrDeviceInfo) GetLanguage() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_DeviceInfo_language_get_caid_daffae03a615fb3a(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrDeviceInfo) SetDevice_name(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_DeviceInfo_device_name_set_caid_daffae03a615fb3a(C.uintptr_t(_swig_i_0), *(*C.swig_type_17)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrDeviceInfo) GetDevice_name() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_DeviceInfo_device_name_get_caid_daffae03a615fb3a(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrDeviceInfo) SetSystem_version(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_DeviceInfo_system_version_set_caid_daffae03a615fb3a(C.uintptr_t(_swig_i_0), *(*C.swig_type_19)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrDeviceInfo) GetSystem_version() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_DeviceInfo_system_version_get_caid_daffae03a615fb3a(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrDeviceInfo) SetMachine(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_DeviceInfo_machine_set_caid_daffae03a615fb3a(C.uintptr_t(_swig_i_0), *(*C.swig_type_21)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrDeviceInfo) GetMachine() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_DeviceInfo_machine_get_caid_daffae03a615fb3a(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrDeviceInfo) SetCarrier_info(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_DeviceInfo_carrier_info_set_caid_daffae03a615fb3a(C.uintptr_t(_swig_i_0), *(*C.swig_type_23)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrDeviceInfo) GetCarrier_info() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_DeviceInfo_carrier_info_get_caid_daffae03a615fb3a(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrDeviceInfo) SetMemory(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_DeviceInfo_memory_set_caid_daffae03a615fb3a(C.uintptr_t(_swig_i_0), *(*C.swig_type_25)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrDeviceInfo) GetMemory() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_DeviceInfo_memory_get_caid_daffae03a615fb3a(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrDeviceInfo) SetDisk(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_DeviceInfo_disk_set_caid_daffae03a615fb3a(C.uintptr_t(_swig_i_0), *(*C.swig_type_27)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrDeviceInfo) GetDisk() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_DeviceInfo_disk_get_caid_daffae03a615fb3a(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrDeviceInfo) SetSys_file_time(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_DeviceInfo_sys_file_time_set_caid_daffae03a615fb3a(C.uintptr_t(_swig_i_0), *(*C.swig_type_29)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrDeviceInfo) GetSys_file_time() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_DeviceInfo_sys_file_time_get_caid_daffae03a615fb3a(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrDeviceInfo) SetModel(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_DeviceInfo_model_set_caid_daffae03a615fb3a(C.uintptr_t(_swig_i_0), *(*C.swig_type_31)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrDeviceInfo) GetModel() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_DeviceInfo_model_get_caid_daffae03a615fb3a(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func (arg1 SwigcptrDeviceInfo) SetTime_zone(arg2 string) {
	_swig_i_0 := arg1
	_swig_i_1 := arg2
	C._wrap_DeviceInfo_time_zone_set_caid_daffae03a615fb3a(C.uintptr_t(_swig_i_0), *(*C.swig_type_33)(unsafe.Pointer(&_swig_i_1)))
	if Swig_escape_always_false {
		Swig_escape_val = arg2
	}
}

func (arg1 SwigcptrDeviceInfo) GetTime_zone() (_swig_ret string) {
	var swig_r string
	_swig_i_0 := arg1
	swig_r_p := C._wrap_DeviceInfo_time_zone_get_caid_daffae03a615fb3a(C.uintptr_t(_swig_i_0))
	swig_r = *(*string)(unsafe.Pointer(&swig_r_p))
	var swig_r_1 string
 swig_r_1 = swigCopyString(swig_r) 
	return swig_r_1
}

func NewDeviceInfo() (_swig_ret DeviceInfo) {
	var swig_r DeviceInfo
	swig_r = (DeviceInfo)(SwigcptrDeviceInfo(C._wrap_new_DeviceInfo_caid_daffae03a615fb3a()))
	return swig_r
}

func DeleteDeviceInfo(arg1 DeviceInfo) {
	_swig_i_0 := arg1.Swigcptr()
	C._wrap_delete_DeviceInfo_caid_daffae03a615fb3a(C.uintptr_t(_swig_i_0))
}

type DeviceInfo interface {
	Swigcptr() uintptr
	SwigIsDeviceInfo()
	SetBoot_time_in_sec(arg2 string)
	GetBoot_time_in_sec() (_swig_ret string)
	SetCountry_code(arg2 string)
	GetCountry_code() (_swig_ret string)
	SetLanguage(arg2 string)
	GetLanguage() (_swig_ret string)
	SetDevice_name(arg2 string)
	GetDevice_name() (_swig_ret string)
	SetSystem_version(arg2 string)
	GetSystem_version() (_swig_ret string)
	SetMachine(arg2 string)
	GetMachine() (_swig_ret string)
	SetCarrier_info(arg2 string)
	GetCarrier_info() (_swig_ret string)
	SetMemory(arg2 string)
	GetMemory() (_swig_ret string)
	SetDisk(arg2 string)
	GetDisk() (_swig_ret string)
	SetSys_file_time(arg2 string)
	GetSys_file_time() (_swig_ret string)
	SetModel(arg2 string)
	GetModel() (_swig_ret string)
	SetTime_zone(arg2 string)
	GetTime_zone() (_swig_ret string)
}

func GenerateCAID(arg1 DeviceInfo) (_swig_ret CaidVector) {
	var swig_r CaidVector
	_swig_i_0 := arg1.Swigcptr()
	swig_r = (CaidVector)(SwigcptrCaidVector(C._wrap_GenerateCAID_caid_daffae03a615fb3a(C.uintptr_t(_swig_i_0))))
	return swig_r
}


