/* ----------------------------------------------------------------------------
 * This file was automatically generated by SWIG (http://www.swig.org).
 * Version 4.0.1
 *
 * This file is not intended to be easily readable and contains a number of
 * coding conventions designed to improve portability and efficiency. Do not make
 * changes to this file unless you know what you are doing--modify the SWIG
 * interface file instead.
 * ----------------------------------------------------------------------------- */

// source: caid.i

#define SWIGMODULE caid

#ifdef __cplusplus
/* SwigValueWrapper is described in swig.swg */
template<typename T> class SwigValueWrapper {
  struct SwigMovePointer {
    T *ptr;
    SwigMovePointer(T *p) : ptr(p) { }
    ~SwigMovePointer() { delete ptr; }
    SwigMovePointer& operator=(SwigMovePointer& rhs) { T* oldptr = ptr; ptr = 0; delete oldptr; ptr = rhs.ptr; rhs.ptr = 0; return *this; }
  } pointer;
  SwigValueWrapper& operator=(const SwigValueWrapper<T>& rhs);
  SwigValueWrapper(const SwigValueWrapper<T>& rhs);
public:
  SwigValueWrapper() : pointer(0) { }
  SwigValueWrapper& operator=(const T& t) { SwigMovePointer tmp(new T(t)); pointer = tmp; return *this; }
  operator T&() const { return *pointer.ptr; }
  T *operator&() { return pointer.ptr; }
};

template <typename T> T SwigValueInit() {
  return T();
}
#endif

/* -----------------------------------------------------------------------------
 *  This section contains generic SWIG labels for method/variable
 *  declarations/attributes, and other compiler dependent labels.
 * ----------------------------------------------------------------------------- */

/* template workaround for compilers that cannot correctly implement the C++ standard */
#ifndef SWIGTEMPLATEDISAMBIGUATOR
# if defined(__SUNPRO_CC) && (__SUNPRO_CC <= 0x560)
#  define SWIGTEMPLATEDISAMBIGUATOR template
# elif defined(__HP_aCC)
/* Needed even with `aCC -AA' when `aCC -V' reports HP ANSI C++ B3910B A.03.55 */
/* If we find a maximum version that requires this, the test would be __HP_aCC <= 35500 for A.03.55 */
#  define SWIGTEMPLATEDISAMBIGUATOR template
# else
#  define SWIGTEMPLATEDISAMBIGUATOR
# endif
#endif

/* inline attribute */
#ifndef SWIGINLINE
# if defined(__cplusplus) || (defined(__GNUC__) && !defined(__STRICT_ANSI__))
#   define SWIGINLINE inline
# else
#   define SWIGINLINE
# endif
#endif

/* attribute recognised by some compilers to avoid 'unused' warnings */
#ifndef SWIGUNUSED
# if defined(__GNUC__)
#   if !(defined(__cplusplus)) || (__GNUC__ > 3 || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4))
#     define SWIGUNUSED __attribute__ ((__unused__))
#   else
#     define SWIGUNUSED
#   endif
# elif defined(__ICC)
#   define SWIGUNUSED __attribute__ ((__unused__))
# else
#   define SWIGUNUSED
# endif
#endif

#ifndef SWIG_MSC_UNSUPPRESS_4505
# if defined(_MSC_VER)
#   pragma warning(disable : 4505) /* unreferenced local function has been removed */
# endif
#endif

#ifndef SWIGUNUSEDPARM
# ifdef __cplusplus
#   define SWIGUNUSEDPARM(p)
# else
#   define SWIGUNUSEDPARM(p) p SWIGUNUSED
# endif
#endif

/* internal SWIG method */
#ifndef SWIGINTERN
# define SWIGINTERN static SWIGUNUSED
#endif

/* internal inline SWIG method */
#ifndef SWIGINTERNINLINE
# define SWIGINTERNINLINE SWIGINTERN SWIGINLINE
#endif

/* exporting methods */
#if defined(__GNUC__)
#  if (__GNUC__ >= 4) || (__GNUC__ == 3 && __GNUC_MINOR__ >= 4)
#    ifndef GCC_HASCLASSVISIBILITY
#      define GCC_HASCLASSVISIBILITY
#    endif
#  endif
#endif

#ifndef SWIGEXPORT
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   if defined(STATIC_LINKED)
#     define SWIGEXPORT
#   else
#     define SWIGEXPORT __declspec(dllexport)
#   endif
# else
#   if defined(__GNUC__) && defined(GCC_HASCLASSVISIBILITY)
#     define SWIGEXPORT __attribute__ ((visibility("default")))
#   else
#     define SWIGEXPORT
#   endif
# endif
#endif

/* calling conventions for Windows */
#ifndef SWIGSTDCALL
# if defined(_WIN32) || defined(__WIN32__) || defined(__CYGWIN__)
#   define SWIGSTDCALL __stdcall
# else
#   define SWIGSTDCALL
# endif
#endif

/* Deal with Microsoft's attempt at deprecating C standard runtime functions */
#if !defined(SWIG_NO_CRT_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_CRT_SECURE_NO_DEPRECATE)
# define _CRT_SECURE_NO_DEPRECATE
#endif

/* Deal with Microsoft's attempt at deprecating methods in the standard C++ library */
#if !defined(SWIG_NO_SCL_SECURE_NO_DEPRECATE) && defined(_MSC_VER) && !defined(_SCL_SECURE_NO_DEPRECATE)
# define _SCL_SECURE_NO_DEPRECATE
#endif

/* Deal with Apple's deprecated 'AssertMacros.h' from Carbon-framework */
#if defined(__APPLE__) && !defined(__ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES)
# define __ASSERT_MACROS_DEFINE_VERSIONS_WITHOUT_UNDERSCORES 0
#endif

/* Intel's compiler complains if a variable which was never initialised is
 * cast to void, which is a common idiom which we use to indicate that we
 * are aware a variable isn't used.  So we just silence that warning.
 * See: https://github.com/swig/swig/issues/192 for more discussion.
 */
#ifdef __INTEL_COMPILER
# pragma warning disable 592
#endif


#include <stddef.h>
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <sys/types.h>



typedef long long intgo;
typedef unsigned long long uintgo;


# if !defined(__clang__) && (defined(__i386__) || defined(__x86_64__))
#   define SWIGSTRUCTPACKED __attribute__((__packed__, __gcc_struct__))
# else
#   define SWIGSTRUCTPACKED __attribute__((__packed__))
# endif



typedef struct { char *p; intgo n; } _gostring_;
typedef struct { void* array; intgo len; intgo cap; } _goslice_;




#define swiggo_size_assert_eq(x, y, name) typedef char name[(x-y)*(x-y)*-2+1];
#define swiggo_size_assert(t, n) swiggo_size_assert_eq(sizeof(t), n, swiggo_sizeof_##t##_is_not_##n)

swiggo_size_assert(char, 1)
swiggo_size_assert(short, 2)
swiggo_size_assert(int, 4)
typedef long long swiggo_long_long;
swiggo_size_assert(swiggo_long_long, 8)
swiggo_size_assert(float, 4)
swiggo_size_assert(double, 8)

#ifdef __cplusplus
extern "C" {
#endif
extern void crosscall2(void (*fn)(void *, int), void *, int);
extern char* _cgo_topofstack(void) __attribute__ ((weak));
extern void _cgo_allocate(void *, int);
extern void _cgo_panic(void *, int);
#ifdef __cplusplus
}
#endif

static char *_swig_topofstack() {
  if (_cgo_topofstack) {
    return _cgo_topofstack();
  } else {
    return 0;
  }
}

static void _swig_gopanic(const char *p) {
  struct {
    const char *p;
  } SWIGSTRUCTPACKED a;
  a.p = p;
  crosscall2(_cgo_panic, &a, (int) sizeof a);
}




#define SWIG_contract_assert(expr, msg) \
  if (!(expr)) { _swig_gopanic(msg); } else


#define SWIG_exception(code, msg) _swig_gopanic(msg)


static _gostring_ Swig_AllocateString(const char *p, size_t l) {
  _gostring_ ret;
  ret.p = (char*)malloc(l);
  memcpy(ret.p, p, l);
  ret.n = l;
  return ret;
}


static void Swig_free(void* p) {
  free(p);
}

static void* Swig_malloc(int c) {
  return malloc(c);
}


#include <typeinfo>
#include <stdexcept>


#include <string>


#include <vector>
#include <stdexcept>


#include <map>
#include <algorithm>
#include <stdexcept>


#include <utility>


#include "caid_alg.h"

SWIGINTERN std::vector< std::pair< std::string,std::string > >::const_reference std_vector_Sl_std_pair_Sl_std_string_Sc_std_string_Sg__Sg__get(std::vector< std::pair< std::string,std::string > > *self,int i){
                int size = int(self->size());
                if (i>=0 && i<size)
                    return (*self)[i];
                else
                    throw std::out_of_range("vector index out of range");
            }
SWIGINTERN void std_vector_Sl_std_pair_Sl_std_string_Sc_std_string_Sg__Sg__set(std::vector< std::pair< std::string,std::string > > *self,int i,std::vector< std::pair< std::string,std::string > >::value_type const &val){
                int size = int(self->size());
                if (i>=0 && i<size)
                    (*self)[i] = val;
                else
                    throw std::out_of_range("vector index out of range");
            }
#ifdef __cplusplus
extern "C" {
#endif

void _wrap_Swig_free_caid_daffae03a615fb3a(void *_swig_go_0) {
  void *arg1 = (void *) 0 ;
  
  arg1 = *(void **)&_swig_go_0; 
  
  Swig_free(arg1);
  
}


void *_wrap_Swig_malloc_caid_daffae03a615fb3a(intgo _swig_go_0) {
  int arg1 ;
  void *result = 0 ;
  void *_swig_go_result;
  
  arg1 = (int)_swig_go_0; 
  
  result = (void *)Swig_malloc(arg1);
  *(void **)&_swig_go_result = (void *)result; 
  return _swig_go_result;
}


std::vector< std::pair< std::string,std::string > > *_wrap_new_CaidVector__SWIG_0_caid_daffae03a615fb3a() {
  std::vector< std::pair< std::string,std::string > > *result = 0 ;
  std::vector< std::pair< std::string,std::string > > *_swig_go_result;
  
  
  result = (std::vector< std::pair< std::string,std::string > > *)new std::vector< std::pair< std::string,std::string > >();
  *(std::vector< std::pair< std::string,std::string > > **)&_swig_go_result = (std::vector< std::pair< std::string,std::string > > *)result; 
  return _swig_go_result;
}


std::vector< std::pair< std::string,std::string > > *_wrap_new_CaidVector__SWIG_1_caid_daffae03a615fb3a(long long _swig_go_0) {
  std::vector< std::pair< std::string,std::string > >::size_type arg1 ;
  std::vector< std::pair< std::string,std::string > > *result = 0 ;
  std::vector< std::pair< std::string,std::string > > *_swig_go_result;
  
  arg1 = (size_t)_swig_go_0; 
  
  result = (std::vector< std::pair< std::string,std::string > > *)new std::vector< std::pair< std::string,std::string > >(arg1);
  *(std::vector< std::pair< std::string,std::string > > **)&_swig_go_result = (std::vector< std::pair< std::string,std::string > > *)result; 
  return _swig_go_result;
}


std::vector< std::pair< std::string,std::string > > *_wrap_new_CaidVector__SWIG_2_caid_daffae03a615fb3a(std::vector< std::pair< std::string,std::string > > *_swig_go_0) {
  std::vector< std::pair< std::string,std::string > > *arg1 = 0 ;
  std::vector< std::pair< std::string,std::string > > *result = 0 ;
  std::vector< std::pair< std::string,std::string > > *_swig_go_result;
  
  arg1 = *(std::vector< std::pair< std::string,std::string > > **)&_swig_go_0; 
  
  result = (std::vector< std::pair< std::string,std::string > > *)new std::vector< std::pair< std::string,std::string > >((std::vector< std::pair< std::string,std::string > > const &)*arg1);
  *(std::vector< std::pair< std::string,std::string > > **)&_swig_go_result = (std::vector< std::pair< std::string,std::string > > *)result; 
  return _swig_go_result;
}


long long _wrap_CaidVector_size_caid_daffae03a615fb3a(std::vector< std::pair< std::string,std::string > > *_swig_go_0) {
  std::vector< std::pair< std::string,std::string > > *arg1 = (std::vector< std::pair< std::string,std::string > > *) 0 ;
  std::vector< std::pair< std::string,std::string > >::size_type result;
  long long _swig_go_result;
  
  arg1 = *(std::vector< std::pair< std::string,std::string > > **)&_swig_go_0; 
  
  result = ((std::vector< std::pair< std::string,std::string > > const *)arg1)->size();
  _swig_go_result = result; 
  return _swig_go_result;
}


long long _wrap_CaidVector_capacity_caid_daffae03a615fb3a(std::vector< std::pair< std::string,std::string > > *_swig_go_0) {
  std::vector< std::pair< std::string,std::string > > *arg1 = (std::vector< std::pair< std::string,std::string > > *) 0 ;
  std::vector< std::pair< std::string,std::string > >::size_type result;
  long long _swig_go_result;
  
  arg1 = *(std::vector< std::pair< std::string,std::string > > **)&_swig_go_0; 
  
  result = ((std::vector< std::pair< std::string,std::string > > const *)arg1)->capacity();
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_CaidVector_reserve_caid_daffae03a615fb3a(std::vector< std::pair< std::string,std::string > > *_swig_go_0, long long _swig_go_1) {
  std::vector< std::pair< std::string,std::string > > *arg1 = (std::vector< std::pair< std::string,std::string > > *) 0 ;
  std::vector< std::pair< std::string,std::string > >::size_type arg2 ;
  
  arg1 = *(std::vector< std::pair< std::string,std::string > > **)&_swig_go_0; 
  arg2 = (size_t)_swig_go_1; 
  
  (arg1)->reserve(arg2);
  
}


bool _wrap_CaidVector_isEmpty_caid_daffae03a615fb3a(std::vector< std::pair< std::string,std::string > > *_swig_go_0) {
  std::vector< std::pair< std::string,std::string > > *arg1 = (std::vector< std::pair< std::string,std::string > > *) 0 ;
  bool result;
  bool _swig_go_result;
  
  arg1 = *(std::vector< std::pair< std::string,std::string > > **)&_swig_go_0; 
  
  result = (bool)((std::vector< std::pair< std::string,std::string > > const *)arg1)->empty();
  _swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_CaidVector_clear_caid_daffae03a615fb3a(std::vector< std::pair< std::string,std::string > > *_swig_go_0) {
  std::vector< std::pair< std::string,std::string > > *arg1 = (std::vector< std::pair< std::string,std::string > > *) 0 ;
  
  arg1 = *(std::vector< std::pair< std::string,std::string > > **)&_swig_go_0; 
  
  (arg1)->clear();
  
}


void _wrap_CaidVector_add_caid_daffae03a615fb3a(std::vector< std::pair< std::string,std::string > > *_swig_go_0, std::pair< std::string,std::string > *_swig_go_1) {
  std::vector< std::pair< std::string,std::string > > *arg1 = (std::vector< std::pair< std::string,std::string > > *) 0 ;
  std::vector< std::pair< std::string,std::string > >::value_type *arg2 = 0 ;
  
  arg1 = *(std::vector< std::pair< std::string,std::string > > **)&_swig_go_0; 
  arg2 = *(std::vector< std::pair< std::string,std::string > >::value_type **)&_swig_go_1; 
  
  (arg1)->push_back((std::vector< std::pair< std::string,std::string > >::value_type const &)*arg2);
  
}


std::pair< std::string,std::string > *_wrap_CaidVector_get_caid_daffae03a615fb3a(std::vector< std::pair< std::string,std::string > > *_swig_go_0, intgo _swig_go_1) {
  std::vector< std::pair< std::string,std::string > > *arg1 = (std::vector< std::pair< std::string,std::string > > *) 0 ;
  int arg2 ;
  std::vector< std::pair< std::string,std::string > >::value_type *result = 0 ;
  std::pair< std::string,std::string > *_swig_go_result;
  
  arg1 = *(std::vector< std::pair< std::string,std::string > > **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  
  try {
    result = (std::vector< std::pair< std::string,std::string > >::value_type *) &std_vector_Sl_std_pair_Sl_std_string_Sc_std_string_Sg__Sg__get(arg1,arg2);
  } catch(std::out_of_range &_e) {
    _swig_gopanic((&_e)->what());
  }
  *(std::vector< std::pair< std::string,std::string > >::value_type **)&_swig_go_result = result; 
  return _swig_go_result;
}


void _wrap_CaidVector_set_caid_daffae03a615fb3a(std::vector< std::pair< std::string,std::string > > *_swig_go_0, intgo _swig_go_1, std::pair< std::string,std::string > *_swig_go_2) {
  std::vector< std::pair< std::string,std::string > > *arg1 = (std::vector< std::pair< std::string,std::string > > *) 0 ;
  int arg2 ;
  std::vector< std::pair< std::string,std::string > >::value_type *arg3 = 0 ;
  
  arg1 = *(std::vector< std::pair< std::string,std::string > > **)&_swig_go_0; 
  arg2 = (int)_swig_go_1; 
  arg3 = *(std::vector< std::pair< std::string,std::string > >::value_type **)&_swig_go_2; 
  
  try {
    std_vector_Sl_std_pair_Sl_std_string_Sc_std_string_Sg__Sg__set(arg1,arg2,(std::pair< std::string,std::string > const &)*arg3);
  } catch(std::out_of_range &_e) {
    _swig_gopanic((&_e)->what());
  }
  
}


void _wrap_delete_CaidVector_caid_daffae03a615fb3a(std::vector< std::pair< std::string,std::string > > *_swig_go_0) {
  std::vector< std::pair< std::string,std::string > > *arg1 = (std::vector< std::pair< std::string,std::string > > *) 0 ;
  
  arg1 = *(std::vector< std::pair< std::string,std::string > > **)&_swig_go_0; 
  
  delete arg1;
  
}


std::pair< std::string,std::string > *_wrap_new_CaidMap__SWIG_0_caid_daffae03a615fb3a() {
  std::pair< std::string,std::string > *result = 0 ;
  std::pair< std::string,std::string > *_swig_go_result;
  
  
  result = (std::pair< std::string,std::string > *)new std::pair< std::string,std::string >();
  *(std::pair< std::string,std::string > **)&_swig_go_result = (std::pair< std::string,std::string > *)result; 
  return _swig_go_result;
}


std::pair< std::string,std::string > *_wrap_new_CaidMap__SWIG_1_caid_daffae03a615fb3a(_gostring_ _swig_go_0, _gostring_ _swig_go_1) {
  std::string arg1 ;
  std::string arg2 ;
  std::pair< std::string,std::string > *result = 0 ;
  std::pair< std::string,std::string > *_swig_go_result;
  
  (&arg1)->assign(_swig_go_0.p, _swig_go_0.n); 
  (&arg2)->assign(_swig_go_1.p, _swig_go_1.n); 
  
  result = (std::pair< std::string,std::string > *)new std::pair< std::string,std::string >(arg1,arg2);
  *(std::pair< std::string,std::string > **)&_swig_go_result = (std::pair< std::string,std::string > *)result; 
  return _swig_go_result;
}


std::pair< std::string,std::string > *_wrap_new_CaidMap__SWIG_2_caid_daffae03a615fb3a(std::pair< std::string,std::string > *_swig_go_0) {
  std::pair< std::string,std::string > *arg1 = 0 ;
  std::pair< std::string,std::string > *result = 0 ;
  std::pair< std::string,std::string > *_swig_go_result;
  
  arg1 = *(std::pair< std::string,std::string > **)&_swig_go_0; 
  
  result = (std::pair< std::string,std::string > *)new std::pair< std::string,std::string >((std::pair< std::string,std::string > const &)*arg1);
  *(std::pair< std::string,std::string > **)&_swig_go_result = (std::pair< std::string,std::string > *)result; 
  return _swig_go_result;
}


void _wrap_CaidMap_first_set_caid_daffae03a615fb3a(std::pair< std::string,std::string > *_swig_go_0, _gostring_ _swig_go_1) {
  std::pair< std::string,std::string > *arg1 = (std::pair< std::string,std::string > *) 0 ;
  std::string *arg2 = 0 ;
  
  arg1 = *(std::pair< std::string,std::string > **)&_swig_go_0; 
  
  std::string arg2_str(_swig_go_1.p, _swig_go_1.n);
  arg2 = &arg2_str;
  
  
  if (arg1) (arg1)->first = *arg2;
  
}


_gostring_ _wrap_CaidMap_first_get_caid_daffae03a615fb3a(std::pair< std::string,std::string > *_swig_go_0) {
  std::pair< std::string,std::string > *arg1 = (std::pair< std::string,std::string > *) 0 ;
  std::string *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(std::pair< std::string,std::string > **)&_swig_go_0; 
  
  result = (std::string *) & ((arg1)->first);
  _swig_go_result = Swig_AllocateString((*result).data(), (*result).length()); 
  return _swig_go_result;
}


void _wrap_CaidMap_second_set_caid_daffae03a615fb3a(std::pair< std::string,std::string > *_swig_go_0, _gostring_ _swig_go_1) {
  std::pair< std::string,std::string > *arg1 = (std::pair< std::string,std::string > *) 0 ;
  std::string *arg2 = 0 ;
  
  arg1 = *(std::pair< std::string,std::string > **)&_swig_go_0; 
  
  std::string arg2_str(_swig_go_1.p, _swig_go_1.n);
  arg2 = &arg2_str;
  
  
  if (arg1) (arg1)->second = *arg2;
  
}


_gostring_ _wrap_CaidMap_second_get_caid_daffae03a615fb3a(std::pair< std::string,std::string > *_swig_go_0) {
  std::pair< std::string,std::string > *arg1 = (std::pair< std::string,std::string > *) 0 ;
  std::string *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(std::pair< std::string,std::string > **)&_swig_go_0; 
  
  result = (std::string *) & ((arg1)->second);
  _swig_go_result = Swig_AllocateString((*result).data(), (*result).length()); 
  return _swig_go_result;
}


void _wrap_delete_CaidMap_caid_daffae03a615fb3a(std::pair< std::string,std::string > *_swig_go_0) {
  std::pair< std::string,std::string > *arg1 = (std::pair< std::string,std::string > *) 0 ;
  
  arg1 = *(std::pair< std::string,std::string > **)&_swig_go_0; 
  
  delete arg1;
  
}


void _wrap_DeviceInfo_boot_time_in_sec_set_caid_daffae03a615fb3a(caid::DeviceInfo *_swig_go_0, _gostring_ _swig_go_1) {
  caid::DeviceInfo *arg1 = (caid::DeviceInfo *) 0 ;
  std::string *arg2 = 0 ;
  
  arg1 = *(caid::DeviceInfo **)&_swig_go_0; 
  
  std::string arg2_str(_swig_go_1.p, _swig_go_1.n);
  arg2 = &arg2_str;
  
  
  if (arg1) (arg1)->boot_time_in_sec = *arg2;
  
}


_gostring_ _wrap_DeviceInfo_boot_time_in_sec_get_caid_daffae03a615fb3a(caid::DeviceInfo *_swig_go_0) {
  caid::DeviceInfo *arg1 = (caid::DeviceInfo *) 0 ;
  std::string *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(caid::DeviceInfo **)&_swig_go_0; 
  
  result = (std::string *) & ((arg1)->boot_time_in_sec);
  _swig_go_result = Swig_AllocateString((*result).data(), (*result).length()); 
  return _swig_go_result;
}


void _wrap_DeviceInfo_country_code_set_caid_daffae03a615fb3a(caid::DeviceInfo *_swig_go_0, _gostring_ _swig_go_1) {
  caid::DeviceInfo *arg1 = (caid::DeviceInfo *) 0 ;
  std::string *arg2 = 0 ;
  
  arg1 = *(caid::DeviceInfo **)&_swig_go_0; 
  
  std::string arg2_str(_swig_go_1.p, _swig_go_1.n);
  arg2 = &arg2_str;
  
  
  if (arg1) (arg1)->country_code = *arg2;
  
}


_gostring_ _wrap_DeviceInfo_country_code_get_caid_daffae03a615fb3a(caid::DeviceInfo *_swig_go_0) {
  caid::DeviceInfo *arg1 = (caid::DeviceInfo *) 0 ;
  std::string *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(caid::DeviceInfo **)&_swig_go_0; 
  
  result = (std::string *) & ((arg1)->country_code);
  _swig_go_result = Swig_AllocateString((*result).data(), (*result).length()); 
  return _swig_go_result;
}


void _wrap_DeviceInfo_language_set_caid_daffae03a615fb3a(caid::DeviceInfo *_swig_go_0, _gostring_ _swig_go_1) {
  caid::DeviceInfo *arg1 = (caid::DeviceInfo *) 0 ;
  std::string *arg2 = 0 ;
  
  arg1 = *(caid::DeviceInfo **)&_swig_go_0; 
  
  std::string arg2_str(_swig_go_1.p, _swig_go_1.n);
  arg2 = &arg2_str;
  
  
  if (arg1) (arg1)->language = *arg2;
  
}


_gostring_ _wrap_DeviceInfo_language_get_caid_daffae03a615fb3a(caid::DeviceInfo *_swig_go_0) {
  caid::DeviceInfo *arg1 = (caid::DeviceInfo *) 0 ;
  std::string *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(caid::DeviceInfo **)&_swig_go_0; 
  
  result = (std::string *) & ((arg1)->language);
  _swig_go_result = Swig_AllocateString((*result).data(), (*result).length()); 
  return _swig_go_result;
}


void _wrap_DeviceInfo_device_name_set_caid_daffae03a615fb3a(caid::DeviceInfo *_swig_go_0, _gostring_ _swig_go_1) {
  caid::DeviceInfo *arg1 = (caid::DeviceInfo *) 0 ;
  std::string *arg2 = 0 ;
  
  arg1 = *(caid::DeviceInfo **)&_swig_go_0; 
  
  std::string arg2_str(_swig_go_1.p, _swig_go_1.n);
  arg2 = &arg2_str;
  
  
  if (arg1) (arg1)->device_name = *arg2;
  
}


_gostring_ _wrap_DeviceInfo_device_name_get_caid_daffae03a615fb3a(caid::DeviceInfo *_swig_go_0) {
  caid::DeviceInfo *arg1 = (caid::DeviceInfo *) 0 ;
  std::string *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(caid::DeviceInfo **)&_swig_go_0; 
  
  result = (std::string *) & ((arg1)->device_name);
  _swig_go_result = Swig_AllocateString((*result).data(), (*result).length()); 
  return _swig_go_result;
}


void _wrap_DeviceInfo_system_version_set_caid_daffae03a615fb3a(caid::DeviceInfo *_swig_go_0, _gostring_ _swig_go_1) {
  caid::DeviceInfo *arg1 = (caid::DeviceInfo *) 0 ;
  std::string *arg2 = 0 ;
  
  arg1 = *(caid::DeviceInfo **)&_swig_go_0; 
  
  std::string arg2_str(_swig_go_1.p, _swig_go_1.n);
  arg2 = &arg2_str;
  
  
  if (arg1) (arg1)->system_version = *arg2;
  
}


_gostring_ _wrap_DeviceInfo_system_version_get_caid_daffae03a615fb3a(caid::DeviceInfo *_swig_go_0) {
  caid::DeviceInfo *arg1 = (caid::DeviceInfo *) 0 ;
  std::string *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(caid::DeviceInfo **)&_swig_go_0; 
  
  result = (std::string *) & ((arg1)->system_version);
  _swig_go_result = Swig_AllocateString((*result).data(), (*result).length()); 
  return _swig_go_result;
}


void _wrap_DeviceInfo_machine_set_caid_daffae03a615fb3a(caid::DeviceInfo *_swig_go_0, _gostring_ _swig_go_1) {
  caid::DeviceInfo *arg1 = (caid::DeviceInfo *) 0 ;
  std::string *arg2 = 0 ;
  
  arg1 = *(caid::DeviceInfo **)&_swig_go_0; 
  
  std::string arg2_str(_swig_go_1.p, _swig_go_1.n);
  arg2 = &arg2_str;
  
  
  if (arg1) (arg1)->machine = *arg2;
  
}


_gostring_ _wrap_DeviceInfo_machine_get_caid_daffae03a615fb3a(caid::DeviceInfo *_swig_go_0) {
  caid::DeviceInfo *arg1 = (caid::DeviceInfo *) 0 ;
  std::string *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(caid::DeviceInfo **)&_swig_go_0; 
  
  result = (std::string *) & ((arg1)->machine);
  _swig_go_result = Swig_AllocateString((*result).data(), (*result).length()); 
  return _swig_go_result;
}


void _wrap_DeviceInfo_carrier_info_set_caid_daffae03a615fb3a(caid::DeviceInfo *_swig_go_0, _gostring_ _swig_go_1) {
  caid::DeviceInfo *arg1 = (caid::DeviceInfo *) 0 ;
  std::string *arg2 = 0 ;
  
  arg1 = *(caid::DeviceInfo **)&_swig_go_0; 
  
  std::string arg2_str(_swig_go_1.p, _swig_go_1.n);
  arg2 = &arg2_str;
  
  
  if (arg1) (arg1)->carrier_info = *arg2;
  
}


_gostring_ _wrap_DeviceInfo_carrier_info_get_caid_daffae03a615fb3a(caid::DeviceInfo *_swig_go_0) {
  caid::DeviceInfo *arg1 = (caid::DeviceInfo *) 0 ;
  std::string *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(caid::DeviceInfo **)&_swig_go_0; 
  
  result = (std::string *) & ((arg1)->carrier_info);
  _swig_go_result = Swig_AllocateString((*result).data(), (*result).length()); 
  return _swig_go_result;
}


void _wrap_DeviceInfo_memory_set_caid_daffae03a615fb3a(caid::DeviceInfo *_swig_go_0, _gostring_ _swig_go_1) {
  caid::DeviceInfo *arg1 = (caid::DeviceInfo *) 0 ;
  std::string *arg2 = 0 ;
  
  arg1 = *(caid::DeviceInfo **)&_swig_go_0; 
  
  std::string arg2_str(_swig_go_1.p, _swig_go_1.n);
  arg2 = &arg2_str;
  
  
  if (arg1) (arg1)->memory = *arg2;
  
}


_gostring_ _wrap_DeviceInfo_memory_get_caid_daffae03a615fb3a(caid::DeviceInfo *_swig_go_0) {
  caid::DeviceInfo *arg1 = (caid::DeviceInfo *) 0 ;
  std::string *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(caid::DeviceInfo **)&_swig_go_0; 
  
  result = (std::string *) & ((arg1)->memory);
  _swig_go_result = Swig_AllocateString((*result).data(), (*result).length()); 
  return _swig_go_result;
}


void _wrap_DeviceInfo_disk_set_caid_daffae03a615fb3a(caid::DeviceInfo *_swig_go_0, _gostring_ _swig_go_1) {
  caid::DeviceInfo *arg1 = (caid::DeviceInfo *) 0 ;
  std::string *arg2 = 0 ;
  
  arg1 = *(caid::DeviceInfo **)&_swig_go_0; 
  
  std::string arg2_str(_swig_go_1.p, _swig_go_1.n);
  arg2 = &arg2_str;
  
  
  if (arg1) (arg1)->disk = *arg2;
  
}


_gostring_ _wrap_DeviceInfo_disk_get_caid_daffae03a615fb3a(caid::DeviceInfo *_swig_go_0) {
  caid::DeviceInfo *arg1 = (caid::DeviceInfo *) 0 ;
  std::string *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(caid::DeviceInfo **)&_swig_go_0; 
  
  result = (std::string *) & ((arg1)->disk);
  _swig_go_result = Swig_AllocateString((*result).data(), (*result).length()); 
  return _swig_go_result;
}


void _wrap_DeviceInfo_sys_file_time_set_caid_daffae03a615fb3a(caid::DeviceInfo *_swig_go_0, _gostring_ _swig_go_1) {
  caid::DeviceInfo *arg1 = (caid::DeviceInfo *) 0 ;
  std::string *arg2 = 0 ;
  
  arg1 = *(caid::DeviceInfo **)&_swig_go_0; 
  
  std::string arg2_str(_swig_go_1.p, _swig_go_1.n);
  arg2 = &arg2_str;
  
  
  if (arg1) (arg1)->sys_file_time = *arg2;
  
}


_gostring_ _wrap_DeviceInfo_sys_file_time_get_caid_daffae03a615fb3a(caid::DeviceInfo *_swig_go_0) {
  caid::DeviceInfo *arg1 = (caid::DeviceInfo *) 0 ;
  std::string *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(caid::DeviceInfo **)&_swig_go_0; 
  
  result = (std::string *) & ((arg1)->sys_file_time);
  _swig_go_result = Swig_AllocateString((*result).data(), (*result).length()); 
  return _swig_go_result;
}


void _wrap_DeviceInfo_model_set_caid_daffae03a615fb3a(caid::DeviceInfo *_swig_go_0, _gostring_ _swig_go_1) {
  caid::DeviceInfo *arg1 = (caid::DeviceInfo *) 0 ;
  std::string *arg2 = 0 ;
  
  arg1 = *(caid::DeviceInfo **)&_swig_go_0; 
  
  std::string arg2_str(_swig_go_1.p, _swig_go_1.n);
  arg2 = &arg2_str;
  
  
  if (arg1) (arg1)->model = *arg2;
  
}


_gostring_ _wrap_DeviceInfo_model_get_caid_daffae03a615fb3a(caid::DeviceInfo *_swig_go_0) {
  caid::DeviceInfo *arg1 = (caid::DeviceInfo *) 0 ;
  std::string *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(caid::DeviceInfo **)&_swig_go_0; 
  
  result = (std::string *) & ((arg1)->model);
  _swig_go_result = Swig_AllocateString((*result).data(), (*result).length()); 
  return _swig_go_result;
}


void _wrap_DeviceInfo_time_zone_set_caid_daffae03a615fb3a(caid::DeviceInfo *_swig_go_0, _gostring_ _swig_go_1) {
  caid::DeviceInfo *arg1 = (caid::DeviceInfo *) 0 ;
  std::string *arg2 = 0 ;
  
  arg1 = *(caid::DeviceInfo **)&_swig_go_0; 
  
  std::string arg2_str(_swig_go_1.p, _swig_go_1.n);
  arg2 = &arg2_str;
  
  
  if (arg1) (arg1)->time_zone = *arg2;
  
}


_gostring_ _wrap_DeviceInfo_time_zone_get_caid_daffae03a615fb3a(caid::DeviceInfo *_swig_go_0) {
  caid::DeviceInfo *arg1 = (caid::DeviceInfo *) 0 ;
  std::string *result = 0 ;
  _gostring_ _swig_go_result;
  
  arg1 = *(caid::DeviceInfo **)&_swig_go_0; 
  
  result = (std::string *) & ((arg1)->time_zone);
  _swig_go_result = Swig_AllocateString((*result).data(), (*result).length()); 
  return _swig_go_result;
}


caid::DeviceInfo *_wrap_new_DeviceInfo_caid_daffae03a615fb3a() {
  caid::DeviceInfo *result = 0 ;
  caid::DeviceInfo *_swig_go_result;
  
  
  result = (caid::DeviceInfo *)new caid::DeviceInfo();
  *(caid::DeviceInfo **)&_swig_go_result = (caid::DeviceInfo *)result; 
  return _swig_go_result;
}


void _wrap_delete_DeviceInfo_caid_daffae03a615fb3a(caid::DeviceInfo *_swig_go_0) {
  caid::DeviceInfo *arg1 = (caid::DeviceInfo *) 0 ;
  
  arg1 = *(caid::DeviceInfo **)&_swig_go_0; 
  
  delete arg1;
  
}


std::vector< std::pair< std::string,std::string > > *_wrap_GenerateCAID_caid_daffae03a615fb3a(caid::DeviceInfo *_swig_go_0) {
  caid::DeviceInfo *arg1 = 0 ;
  std::vector< std::pair< std::string,std::string > > result;
  std::vector< std::pair< std::string,std::string > > *_swig_go_result;
  
  arg1 = *(caid::DeviceInfo **)&_swig_go_0; 
  
  result = caid::GenerateCAID((caid::DeviceInfo const &)*arg1);
  *(std::vector< std::pair< std::string,std::string > > **)&_swig_go_result = new std::vector< std::pair< std::string,std::string > >(result); 
  return _swig_go_result;
}


#ifdef __cplusplus
}
#endif

